# Generated by Django 3.2 on 2021-04-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_link', models.URLField()),
                ('short_link', models.URLField(blank=True, null=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
