# Generated by Django 3.2 on 2021-04-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_link_custom_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='custom_link',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='input_link',
            field=models.URLField(max_length=10000),
        ),
    ]
